### ISSUE TITLE
Update docs for cloning procedure

### ISSUE THREAD

**Issue by mattwr18** [Human-Connection/Nitro-Documentation#29]
We are now going to recommend developer's clone our repos directly as forks do not have access to the encrypted environment variables in the Travis build. 

This means that no `PR`s from forks will pass the build
see https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml

**Comment by roschaefer** [comment]
@mattwr18 I have published `CYPRESS_TOKEN` on our Travis build: https://travis-ci.com/Human-Connection/Human-Connection/builds/106086040#L923. I think it's OK to fork, we should simply encourage new contributors to ask for write permissions instead of forking the repo.

I'll close this for now, feel free to re-open if you think we should keep this issue to update the docs.
